version: '3.9'
services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   networks:
  #     - backend
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - backend
    volumes: 
      - cache:/data
networks:
  backend:
volumes:
  cache:
    driver: local
